name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - github_actions

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: ./
      - name: Create k8s cluster
        uses: actions/create-cluster-action@v1
        id: create-cluster
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DigitalOceanToken }}